finance/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from finance.views import *

app_name='finance'
urlpatterns = [
	path('',views.index,name="finance_index"),
	path('addorder/',views.AddOrder,name="addorder"),
    path('searchorder/',views.SearchOrderView.as_view(),name="searchorder"),
    path('change_order/',views.change_order,name="change_order"),
    path('delete_order/',views.delete_order,name="delete_order"),
    path('orderdetail/',views.orderdetail,name="orderdetail"),
    path('addproduce/',views.AddProduceView,name="addproduce"),
    path('deleteproduce/',views.deleteproduce,name="deleteproduce"),
    path('changeproduce/<int:nid>/',views.changeproduce,name="changeproduce"),
    path('searchproduce/',views.SearchProduceView.as_view(),name="searchproduce"),
    path('searchoffer/',views.SearchOfferView.as_view(),name="searchoffer"),
    path('offerdetail/',views.SearchOfferDetailView.as_view(),name="searchofferdetail"),
    path('searchorderdetail/',views.SearchOrderDetailView.as_view(),name="searchorderdetail"),
    path('addoffer/',views.AddofferView.as_view(),name="addoffer"),
    path('dooffer/',views.dooffer,name="dooffer"),
    path('deloffer/<str:offerid>/',views.deloffer,name="deloffer"),
    path('delofferdetail/',views.delofferdetail,name="delofferdetail"),
    path('changeoffer/',views.changeoffer,name="changeoffer"),
    path('ordercollectionadd/<str:order_id>/',views.OrderCollectionCreate.as_view(),name="addordercollection"),
    path('ordercollectionupdate/<str:order_id>/<int:pk>/',views.OrderCollectionUpdate.as_view(),name="updateordercollection"),
    path('ordercollectiondelete/<str:order_id>/<int:pk>/',views.OrderCollectionDelete.as_view(),name="deleteordercollection"),
    path('ordercostadd/<str:order_id>/',views.OrderCostCreate.as_view(),name="addordercost"),
    path('ordercostupdate/<str:order_id>/<int:pk>/',views.OrderCostUpdate.as_view(),name="updateordercost"),
    path('ordercostdelete/<str:order_id>/<int:pk>/',views.OrderCostDelete.as_view(),name="deleteordercost"),
    path('orderdetailadd/<str:order_id>/',views.OrderDetailCreate.as_view(),name="addorderdetail"),
    path('orderdetailupdate/<str:order_id>/<int:pk>/',views.OrderDetailUpdate.as_view(),name="updateorderdetail"),
    path('orderdetaildelete/<str:order_id>/<int:pk>/',views.OrderDetailDelete.as_view(),name="deleteorderdetail"),
]

huang/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('finance/', include('finance.urls')),
]

finance/forms.py
from django import forms
from finance.models import *

class AddProduceForm(forms.ModelForm):
    class Meta:
        model = produce
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super(AddProduceForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
class order_collectionForm(forms.ModelForm):

    class Meta:
        model = order_collection
        fields = "__all__"

finance/views.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from finance.models import *
from django.db import connections
from django.forms.models import model_to_dict  
import json
from django.core.serializers import serialize
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage,InvalidPage
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django import forms
from finance.forms import *
from django.utils import timezone
from django.utils.timezone import now, localtime
from django.db.models import Q,F
from decimal import Decimal



# Create your views here.
def index(request):
	return render(request,'finance/app_head.html')



# 使用form组件实现注册方式
def AddProduceView(request):
	error_msg=''
	form_obj = AddProduceForm()         # 实例化一个对象
	if request.method == "POST":
		# 实例化form对象的时候，把post提交过来的数据直接传进去
		form_obj = AddProduceForm(request.POST)
		# 调用form_obj校验数据的方法
		if form_obj.is_valid():
			form_obj.save()
			error_msg="添加成功"
	if request.method=="GET":
		id=request.GET.get("id")
		if id:
			k=produce.objects.get(id=id)
			k_dict = model_to_dict(k)
			form_obj = AddProduceForm(k_dict)
		

	content={'error_msg':error_msg,
			'form_obj':form_obj,    
	}
	return render(request, "finance/addproduce.html", content)
class SearchProduceView(ListView): 
	model=produce
	ordering = 'id'   #以id字段排序
	context_object_name = 'produce_list'  # 传到template中的list



	
	def get_queryset(self): 
		produce_list=produce.objects.all()

		producename=self.request.GET.get("producename")
		if producename:
			produce_list=produce_list.filter(producename__contains=producename)
		return produce_list
	

	def get_context_data(self, **kwargs):
		context = super(SearchProduceView, self).get_context_data(**kwargs)
		context['params'] = [f for f in produce._meta.fields]        
		return context

def deleteproduce(request):
	if request.method=="GET":
		id=request.GET.get("id")
		produce.objects.filter(id=id).delete()

	return redirect(reverse('finance:searchproduce'))
def changeproduce(request,nid):
	k=produce.objects.get(id=nid)
	error_msg=''
	form_obj = AddProduceForm()         # 实例化一个对象
	if request.method == "POST":
		# 实例化form对象的时候，把post提交过来的数据直接传进去
		form_obj = AddProduceForm(request.POST,instance=k)
		# 调用form_obj校验数据的方法
		if form_obj.is_valid():
			form_obj.save()
			error_msg="修改成功"
	if request.method=="GET":
			form_obj = AddProduceForm(instance=k)
		

	content={'error_msg':error_msg,
	'form_obj':form_obj,
	'nid':nid,    
	}
	return render(request, "finance/changeproduce.html", content)
class AddofferView(ListView): 
	model=produce
	ordering = 'id'   #以id字段排序
	context_object_name = 'produce_list'  # 传到template中的list
	template_name = "finance/add_offer_list.html"  #渲染页面



	
	def get_queryset(self): 
		produce_list=produce.objects.filter(id=0)
		list_pids=self.request.GET.getlist("chb")
		pid=self.request.GET.get("pid")
		pids=self.request.GET.get("pids")
		if pid:
				if pids!='':
					list_pids=pids.split(',')                
				else:
					list_pids=[]


				if ',' in pid:
					list_pid=pid.split(',')
					list_pids=list_pids+list_pid
				else:
					list_pids.append(pid)

		if not list_pids:
				list_pids=[]
			#去重
		list_pids=list(set(list_pids))
			#排序
		list_pids = list(map(int, list_pids))
		list_pids.sort()
		produce_list=produce.objects.filter(id__in=list_pids)
				
			
		return produce_list
	

	def get_context_data(self, *args,**kwargs):
		context = super(AddofferView, self).get_context_data(**kwargs)
		list_pids=self.request.GET.getlist("chb")
		pid=self.request.GET.get("pid")
		pids=self.request.GET.get("pids")
		if pid:
				if pids!='':
					list_pids=pids.split(',')                
				else:
					list_pids=[]


				if ',' in pid:
					list_pid=pid.split(',')
					list_pids=list_pids+list_pid
				else:
					list_pids.append(pid)
		if not list_pids:
				list_pids=[]


			#去重
		list_pids=list(set(list_pids))
			#排序
		list_pids = list(map(int, list_pids))
		list_pids.sort()

		pids=','.join(list(map(str, list_pids)))
	   
				
		context['pids'] = pids
		context['pid'] = pid
		return context

def dooffer(request):
	
	if request.method=="POST":
		pids=request.POST.get("pids",None)
		xunnum=request.POST.getlist('xunnum')
		beinum=request.POST.getlist('beinum')
		exchangerate=request.POST.getlist('exchangerate')
		customer=request.POST.get('customer')
		customersource=request.POST.get('customersource')
		country=request.POST.get('country')
		level=request.POST.get('level')


		if pids and xunnum and beinum and exchangerate:
			create_time=timezone.localtime()
			offerid="QU"+create_time.strftime("%Y%m%d%H%M%S")

			list_pids=pids.split(',')

			cursor = connections['default'].cursor()


			n=0
			length = len(list_pids)
			sqlstr=""
			for id,xun,bei,rate in zip(list_pids,xunnum,beinum,exchangerate):
				if xun=='' or bei=='' or rate=='' or customer=='' or customersource=='' or country=='' or level=='':
					error_msg='有必输项没有填写！'
					content={'error_msg':error_msg,}
					return render(request, "finance/error.html", content)
				n+=1
				if n==length:
					houunion=""                
				else:
					houunion=" union all "
				sqlstr=sqlstr+"select id,producename,describe,factoryprice,'{0}' as xunnum,'{1}' as beinum,'{2}' as exchangerate,round(factoryprice*{1},3) as beiprice,round((factoryprice*{1}-factoryprice)*{0},3) as profitsrmb,round(factoryprice*{1}/{2},3) as usdprice,round(factoryprice*{1}*{0}/{2},3) as usdtotalprice,round({0}.0/eachpacknum,3) as number,round(plong*pwide*phigh*{0}/(eachpacknum*1000000.0),3) as totalvolume,round(plong*pwide*phigh/5000.0,3) as unitweight,round((plong*pwide*phigh*{0})/(5000.0*eachpacknum),3) as totalvolumeweight,round(({0}.0/eachpacknum)*(weight*eachpacknum/1000.0+1),3) as totalweight,'{4}' as offerid from finance_produce where id={3} ".format(xun,bei,rate,id,offerid)
				sqlstr=sqlstr+houunion

			
			
			cursor.execute(sqlstr)
			offerdetail_list=cursor.fetchall()

			#保存报价信息
			sqlstrinsert='''insert into finance_offer(offerid,customer,customersource,country,level,createdatetime)  
						 values('{0}','{1}','{2}','{3}','{4}','{5}')'''.format(offerid,customer,customersource,country,level,timezone.localtime())
			cursor.execute(sqlstrinsert)
			sqlstrinsert='''insert into finance_offerdetail(offer_id,produce_id,xunnum,beinum,exchangerate,beiprice,profitsrmb,usdprice,usdtotalprice,number,totalvolume,unitweight,totalvolumeweight,totalweight,createdatetime)
						  select offerid,id,xunnum,beinum,exchangerate,beiprice,profitsrmb,usdprice,usdtotalprice,number,totalvolume,unitweight,totalvolumeweight,totalweight,'{1}' from ({0})'''.format(sqlstr,timezone.localtime())
			cursor.execute(sqlstrinsert)
	   


		cursor.close()
	url=reverse('finance:searchofferdetail')+"?offerid={0}".format(offerid)
	return redirect(url)
def changeoffer(request):
	error_msg=""
	if request.method=="POST":
		offerid=request.POST.get("offerid",None)
		list_pids=request.POST.getlist('produceid')
		xunnum=request.POST.getlist('xunnum')
		beinum=request.POST.getlist('beinum')
		exchangerate=request.POST.getlist('exchangerate')
		customer=request.POST.get('customer')
		customersource=request.POST.get('customersource')
		country=request.POST.get('country')
		level=request.POST.get('level')
		cursor = connections['default'].cursor()

		if offerid:
			sqlstr="update finance_offer set customer='{0}',customersource='{1}',country='{2}',level='{3}' where offerid='{4}'".format(customer,customersource,country,level,offerid)
			cursor.execute(sqlstr)
			#print(sqlstr)

			for id,xun,bei,rate in zip(list_pids,xunnum,beinum,exchangerate):
				sqlstr='''update finance_offerdetail set 
				 xunnum='{0}'
				,beinum='{1}'
				,exchangerate='{2}'
				,beiprice=(select round(factoryprice*{1},3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,profitsrmb=(select round((factoryprice*{1}-factoryprice)*{0},3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,usdprice=(select round(factoryprice*{1}/{2},3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,usdtotalprice=(select round(factoryprice*{1}*{0}/{2},3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,number=(select round({0}.0/eachpacknum,3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,totalvolume=(select round(plong*pwide*phigh*{0}/(eachpacknum*1000000.0),3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,unitweight=(select round(plong*pwide*phigh/5000.0,3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,totalvolumeweight=(select round((plong*pwide*phigh*{0})/(5000.0*eachpacknum),3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				,totalweight=(select round(({0}.0/eachpacknum)*(weight*eachpacknum/1000.0+1),3) from finance_produce where finance_produce.id=finance_offerdetail.produce_id)
				 where  offer_id='{4}' and produce_id='{3}' '''.format(xun,bei,rate,id,offerid)
				cursor.execute(sqlstr)
				#print(sqlstr)
		error_msg="保存成功"
		cursor.close()
	url=reverse('finance:searchofferdetail')+"?offerid={0}&error_msg={1}".format(offerid,error_msg)
	return redirect(url)

class SearchOfferView(ListView): 
	model=offer
	ordering = 'offerid'   #以id字段排序
	context_object_name = 'offer_list'  # 传到template中的list



	
	def get_queryset(self): 
		offer_list=offer.objects.all()

		offerid=self.request.GET.get("offerid")
		if offerid:
			offer_list=offer_list.filter(offerid__contains=offerid)
		return offer_list
	

	def get_context_data(self, **kwargs):
		context = super(SearchOfferView, self).get_context_data(**kwargs)
		context['params'] = [f for f in offer._meta.fields]        
		return context
class SearchOfferDetailView(ListView): 
	model=offerdetail
	ordering = 'id'   #以id字段排序
	context_object_name = 'offerdetail_list'  # 传到template中的list

	def get_queryset(self): 

finance/templates/finance/add_offer_list.html
<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<title>报价计算</title>
</head>

<body>
{% load static  %}
<script src="{% static 'js/setchecked.js' %}"></script>	
{% include "finance/produce_head.html" %}
<p><font size="5" face="华文行楷">报价计算</font></p>

<div class="panel panel-default">
<form method="GET" action="{% url 'finance:addoffer' %}" class="form-inline" role="form">
	<input type="hidden" name="pids" value="{{ pids }}">
      <div class="panel-heading"> 
	{% csrf_token %}
	<div class="form-group">  
		<input type="input" name="pid" class="form-control" placeholder="产品id(,)" value="{{ request.GET.pid }}">
	 </div> 
	<button type="submit" class="btn btn-primary">+增加</button>
</div>
</form>
</div>
<hr>
<div align="center">
	<form method="POST" action="{% url 'finance:dooffer' %}" class="form-inline" role="form" target="_blank">
		{% csrf_token %}
		<input type="hidden" name="pids" value="{{ pids }}">
		<div class="form-group">  
			<input type="input" name="customer" class="form-control" placeholder="客户">
			<input type="input" name="customersource" class="form-control" placeholder="客户来源">
			<input type="input" name="country" class="form-control" placeholder="国家">
			<select name="level" class="form-control" placeholder="重要程度">
				<option>1</option>
				<option>2</option>
				<option>3</option>
				<option>4</option>
				<option>5</option>
			</select>
	 	</div> 
		<button type="submit" class="btn btn-primary">生成报价单</button>
	<table id="example" class="display" cellspacing="0" width="100%">
		<thead>
			<tr>
			<th><input type="checkbox" name="chb[]" id="all" onclick="setchecked(this)"></th>
			<th><font size="1">id</font></th>			
			<th><font size="1">产品名称</font></th>
			<th><font size="1">产品描述</font></th>
			<th><font size="1">询价数量</font></th>
			<th><font size="1">倍数</font></th>
			<th><font size="1">汇率</font></th>
		</tr>
		</thead>
		<tbody>
	{% if produce_list %}	
	{% for k in produce_list %}	
	<tr>
		<td><font size="1"><input type="checkbox" name="chb[]" value="" onclick="setchecked(this)"></font></td>
		<td><font size="1">{{ k.id }}</font></td>
		<td><font size="1">{{ k.producename }}</font></td>
		<td><font size="1">{{ k.describe }}</font></td>
		<td><font size="1"><input type="input" name="xunnum" class="form-control" placeholder="询价数量"></font></td>
		<td><font size="1"><input type="input" name="beinum" class="form-control" placeholder="倍数" value="1.5"></font></td>
		<td><font size="1"><input type="input" name="exchangerate" class="form-control" placeholder="汇率" value="6.5"></font></td>
	</tr>
	{% endfor %}
	{% else %}
	<tr>
		<td colspan="7" height="117"><font size="1">请添加报价产品</font></td>
	</tr>
	{% endif %}
	
</tbody>
</table>
</form>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
     $(document).ready(function() {
        $('#example').DataTable({
                 "pagingType":   "full_numbers",
                 "searching" : false,
           });
    } );
</script>
</body>

</html>

finance/templates/finance/offerdetail_list.html
<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<title>报价</title>
</head>

<body>
<p><font size="5" face="华文行楷">报价</font></p>

<div align="center">
	<form method="POST" action="" class="form-inline" role="form">
		{% csrf_token %}
		<input type="hidden" name="offerid" value="{{ offerid }}">
		<p><button type="submit" class="btn btn-primary" formaction="{% url 'finance:changeoffer' %}">修改保存</button>&nbsp;&nbsp;&nbsp;
		   <button type="submit" class="btn btn-primary" formaction="{% url 'finance:addorder' %}">新增订单</button>
		</p>
	    <p><font size="2" color="red">{% if error_msg %}{{error_msg}}{% endif %}</font></p>

<div align="left">
<table width="800">
	<tr>
		<td><font size="1">报价单编号：</font></td>
		<td><font size="1">{{ offerid }}</font></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td><font size="1">客户：</font></td>
		<td><font size="1"><input type="input" name="customer" class="form-control" placeholder="客户" value="{{ offer_list.customer }}"></font></td>
		<td><font size="1">来源：</font></td>
		<td><font size="1"><input type="input" name="customersource" class="form-control" placeholder="客户来源" value="{{ offer_list.customersource }}"></font></td>
		<td><font size="1">国家：</font></td>
		<td><font size="1"><input type="input" name="country" class="form-control" placeholder="国家" value="{{ offer_list.country }}"></font></td>
		<td><font size="1">重要性：</font></td>
		<td>
		<select name="level" class="form-control" placeholder="重要程度">
			{% for i in level_list %}
			{% if i == offer_list.level %}
				<option selected >{{i}}</option>
			{% else %}
				<option>{{i}}</option>
			{% endif %}
			{% endfor %}
			</select></td>
	</tr>
</table>
</div>
	<table id="example" class="display" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th><input type="checkbox" name="chb" id="all" onclick="setchecked(this)"></th>
		{% if params %}
			{% for result_recode in params %}
			<th><font size="1">{{result_recode.verbose_name}}</font></th>
			{% endfor %}
			{% endif %}
			<th><font size="1">操作</font></th>
		</tr>
		</thead>
		<tbody>
	{% if offerdetail_list %}	
	{% for k in offerdetail_list %}	
	<tr>
		<td><font size="1"><input type="checkbox" name="chb" value="{{ k.id }}" onclick="setchecked(this)"></font></td>
		<td><font size="1">{{ k.id }}</font></td>
		<td><font size="1">{{ k.offer.offerid }}</font></td>
		<td><font size="1">{{ k.produce.id }}</font></td>		
		<input type="hidden" name="produceid" value="{{ k.produce.id }}">
		<td><font size="1"><input type="input" name="xunnum" class="form-control" placeholder="询价数量" value={{ k.xunnum }} size="4"></font></td>
		<td><font size="1"><input type="input" name="beinum" class="form-control" placeholder="倍数" value={{ k.beinum }} size="2"></font></td>
		<td><font size="1"><input type="input" name="exchangerate" class="form-control" placeholder="汇率" value={{ k.exchangerate }} size="4"></font></td>
		<td><font size="1">{{ k.beiprice }}</font></td>
		<td><font size="1">{{ k.profitsrmb }}</font></td>
		<td><font size="1">{{ k.usdprice }}</font></td>
		<td><font size="1">{{ k.usdtotalprice }}</font></td>
		<td><font size="1">{{ k.number }}</font></td>
		<td><font size="1">{{ k.totalvolume }}</font></td>
		<td><font size="1">{{ k.unitweight }}</font></td>
		<td><font size="1">{{ k.totalvolumeweight }}</font></td>
		<td><font size="1">{{ k.totalweight }}</font></td>
		<td><font size="1">{{ k.createdatetime |date:"Y-m-d H:i:s" }}</font></td>
		<td><font size="1"><a href="{% url 'finance:delofferdetail'  %}?offerid={{k.offer.offerid}}&id={{k.id }}">删除</a></font></td>
	</tr>
	{% endfor %}
	{% else %}
	<tr>
		<td colspan="6" height="117"><font size="1">{{ error_msg }}</font></td>
	</tr>
	{% endif %}
	
</tbody>
</table>
</form>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
     $(document).ready(function() {
        $('#example').DataTable({
                 "pagingType":   "full_numbers",
                 "searching" : false,
           });
    } );
</script>
</body>

</html>

finance/templates/finance/produce_head.html
<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>订单管理系统</title>
</head>

<body>

<p><font size="5" face="华文行楷">产品管理</font></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p align="right"><font size="2"><a href="{% url 'index' %}" style="text-decoration:none">首页</a>
<hr>
<p><a href="{% url 'finance:searchproduce' %}">产品查询</a>&nbsp;<a href="{% url 'finance:addproduce' %}">新增产品</a>&nbsp;<a href="{% url 'finance:searchoffer' %}">报价管理</a></p>
<hr>
<p>&nbsp;</p>

</body>

</html>

finance/templates/finance/produce_list.html
<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<title>查询产品</title>
</head>

<body>
{% load static  %}
<script src="{% static 'js/setchecked.js' %}"></script>	
{% include "finance/produce_head.html" %}
<p><font size="5" face="华文行楷">查询</font></p>

<div class="panel panel-default">
<form method="GET" action="" class="form-inline" role="form" target="_blank">
<div class="panel-heading"> 
	{% csrf_token %}
		<button type="submit" class="btn btn-primary" formaction="{% url 'finance:addoffer' %}">新增报价</button>
</div>

<hr>
<div align="center">
	<table id="example" class="display" width="100%">
		<thead>
			<tr>
			<th><input type="checkbox" name="on" id="all" onclick="setchecked(this)"></th>
			{% if params %}
			{% for result_recode in params %}
			<th><font size="1">{{result_recode.verbose_name}}</font></th>
			{% endfor %}
			{% endif %}
			<th><font size="1">增</font></th>
			<th><font size="1">删</font></th>
			<th><font size="1">改</font></th>
		</tr>
		</thead>
		<tbody>
	{% if produce_list %}	
	{% for k in produce_list %}	
	<tr>
		<td><font size="1"><input type="checkbox" name="chb" value="{{ k.id }}" onclick="setchecked(this)"></font></td>
		<td><font size="1">{{ k.id }}</font></td>
		<td><font size="1">{{ k.category }}</font></td>
		<td><font size="1">{{ k.producename }}</font></td>
		<td><font size="1">{{ k.describe }}</font></td>
		<td><font size="1">{{ k.pronumber }}</font></td>
		<td><font size="1">{{ k.factorynumber }}</font></td>
		<td><font size="1">{{ k.icon }}</font></td>
		<td><font size="1">{{ k.manufacturer }}</font></td>
		<td><font size="1">{{ k.size }}</font></td>
		<td><font size="1">{{ k.weight }}</font></td>
		<td><font size="1">{{ k.packdetailsnote }}</font></td>
		<td><font size="1">{{ k.eachpacknum }}</font></td>
		<td><font size="1">{{ k.plong }}</font></td>
		<td><font size="1">{{ k.pwide }}</font></td>
		<td><font size="1">{{ k.phigh }}</font></td>
		<td><font size="1">{{ k.factoryprice }}</font></td>
		<td><font size="1">{{ k.unit }}</font></td>
		<td><font size="1">{{ k.freightdesc }}</font></td>
		<td><font size="1">{{ k.taxprice }}</font></td>
		<td><font size="1">{{ k.taxpointnote }}</font></td>
		<td><font size="1">{{ k.createdatetime |date:"Y-m-d H:i:s" }}</font></td>
		<td><font size="1"><a href="{% url 'finance:addproduce' %}?id={{k.id}}">增加</a></font></td>
		<td><font size="1"><a href="{% url 'finance:deleteproduce' %}?id={{k.id}}">删除</a></font></td>
		<td><font size="1"><a href="{% url 'finance:changeproduce' k.id %}">修改</a></font></td>
	</tr>
	{% endfor %}
	{% else %}
	<tr>
		<td colspan="27" height="117"><font size="1">找到0条数据</font></td>
	</tr>
	{% endif %}
	
</tbody>
	</table>
</div>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
     $(document).ready(function() {
    $('#example').DataTable( {
        "pagingType": "full_numbers"
    } );
} );
</script>
</body>

</html>